version: 2.1

jobs:
  build:
    docker:
      - image: cimg/java:17.0
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      # Assemble project
      - run: ./gradlew assemble -x test

      # Run tests
      - run: ./gradlew test
      - store_test_results:
          path: build/test-results/test

      # Build project
      - run: ./gradlew build -x test -x check

      # Build and tag Docker image
      - run:
          name: Build Docker Image
          command: |
            docker build -f src/main/docker/Dockerfile.jvm -t quarkus/demo-for-ci-jvm --label "runnumber=${CIRCLE_BUILD_NUM}" .
            docker tag quarkus/demo-for-ci-jvm quarkus/demo-for-ci-jvm:circleci-latest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
