version: 2.1

orbs:
  gradle: circleci/gradle@3.0.0

workflows:
  version: 2
  build-deploy:
    jobs:
      - gradle/test:
          executor:
            name: gradle/default
            tag: "17.0"
          test_command: test
