version: 2.1

workflows:
  main:
    jobs:
      - build
      
jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: ./gradlew assemble -x test
      - run: ./gradlew test
      - run: ./gradlew build -x test
